name: with_bloc
description: A widget to create and manage BLoCs implemented on top of ValueNotifier, such as StateQueue.
version: 2.0.0
authors:
  - Timm Preetz <timm.preetz@aboutyou.com>
  - Henri Beck <henri.beck@aboutyou.com>
homepage: https://github.com/aboutyou/dart_packages/tree/master/packages/with_bloc
repository: https://github.com/aboutyou/dart_packages

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.0.0

dev_dependencies:
  test: any

  pedantic: ^1.8.0+1

  state_queue:
    git:
      url: git://github.com/swipelab/dart_packages.git
      path: packages/state_queue

  flutter_test:
    sdk: flutter
