name: state_queue_test
description: Testing utilities for `StateQueue`
version: 1.0.0
homepage: https://github.com/aboutyou/dart_packages/tree/master/packages/state_queue_teste
repository: https://github.com/aboutyou/dart_packages

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0 <3.0.0"

dependencies:
  
  flutter:
    sdk: flutter
  meta: ^1.0.0

  pending_operations: ^2.0.0

  state_queue:
    git:
      url: git://github.com/swipelab/dart_packages.git
      path: packages/state_queue

  test: ^1.0.0

dev_dependencies:
  
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1
